### ISSUE TITLE
.abapgit.xml

### ISSUE THREAD

**Issue by larshp** [jasper07/Teched17#1]
Hi,
The `.abapgit.xml` file should be located in the root folder of the project. I think the current setup also works, but it just ignores the .abapgit.xml file

**Comment by jasper07** [comment]
Hi Lars
Thanks for the prompting, looked at the help on [.abapgit.xml](http://larshp.github.io/abapGit/ref-dot-abapgit.html)

Made relevant changes around ignore and start folder and now works as expected.

Any other obvious mistakes i made?

Cheers
JSP

**Comment by larshp** [comment]
nope, everything looks okay now, but have not tried installing it yet

I will update the abapGit documentation with a note on where the file should be located 😄
