### ISSUE TITLE
Mistake in Readme for the Flight Annotation Model

### ISSUE THREAD

**Issue by albanleong** [jasper07/Teched17#2]
In the README steps for creation of the FLIGHT Annotation Model, it had ZTE_FLIGHT**OVP**_ANNO_MDL listed and the screenshot is incorrect. Also, the following steps to assign the FLIGHT Annotation Model to the Flight Service was listed as "And assign the Annotation Model ZTE_FLIGHT**OVP**_ANNO_MDL to the ZTE_FLIGHT_SRV service"

Anyway, I attended your TechEd session and it was GREAT!!! Thank you for taking the time to not only prepare the presentation and share your experience but at the same time share the work as well! Thanks!

Btw, I did manage to follow through the steps and got it to work on my local ABAP server. Again, can't thank you enough for taking the time and effort to put this together!

**Comment by jasper07** [comment]
Hi Alban
Thanks a lot for raising this issue, hopefully i fixed the issue.

Also thanks for confirming that you were able to import and run the code

Enjoy the rest of Teched
Cheers
John P
